config/routes.rb
Rails.application.routes.draw do
  resources :catelogies
  resources :microposts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catelogy.rb
class Catelogy < ApplicationRecord
    has_many :microposts
    validates :catelogyName,presence: true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    belongs_to :catelogy
    has_rich_text :content
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
    has_one_attached :avatar
    validates :name, presence: true;
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,message: "email wrong" }, presence: true
    max_paginates_per 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catelogies_controller.rb
class CatelogiesController < ApplicationController
  before_action :set_catelogy, only: [:show, :edit, :update, :destroy]

  # GET /catelogies
  # GET /catelogies.json
  def index
    @catelogies = Catelogy.all
  end

  # GET /catelogies/1
  # GET /catelogies/1.json
  def show
  end

  # GET /catelogies/new
  def new
    @catelogy = Catelogy.new
  end

  # GET /catelogies/1/edit
  def edit
  end

  # POST /catelogies
  # POST /catelogies.json
  def create
    @catelogy = Catelogy.new(catelogy_params)

    respond_to do |format|
      if @catelogy.save
        format.html { redirect_to @catelogy, notice: 'Catelogy was successfully created.' }
        format.json { render :show, status: :created, location: @catelogy }
      else
        format.html { render :new }
        format.json { render json: @catelogy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catelogies/1
  # PATCH/PUT /catelogies/1.json
  def update
    respond_to do |format|
      if @catelogy.update(catelogy_params)
        format.html { redirect_to @catelogy, notice: 'Catelogy was successfully updated.' }
        format.json { render :show, status: :ok, location: @catelogy }
      else
        format.html { render :edit }
        format.json { render json: @catelogy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catelogies/1
  # DELETE /catelogies/1.json
  def destroy
    @catelogy.destroy
    respond_to do |format|
      format.html { redirect_to catelogies_url, notice: 'Catelogy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catelogy
      @catelogy = Catelogy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catelogy_params
      params.require(:catelogy).permit(:catelogyName)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
 

  def index
    if params[:value]
    @b = params[:value]
    else @b = ""
    end
    if params[:catelogyValue]
      @pc = params[:catelogyValue]
      else @pc= ""
      end
    @micropostsAll = Micropost.all
    @q = Micropost.ransack(content_or_user_name_cont: @b, catelogy_id_in: @pc)
    @microposts = @q.result.order(:name).page params[:page]
  end
  
  def search_params
    return nil unless params[:micropost_list]
    params.require(:micropost_list).permit :content_or_user_id_or_catelogy_id
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id, :catelogy_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all
  # end

  def index
    if params[:value]
    @b = params[:value]
    else @b = ''
    end
    @q = User.ransack(name_cont: @b, email_cont: @b, m: 'or')
    @users = @q.result.order(:name).page params[:page]
  end
  
  def search_params
    return nil unless params[:user_list]
    params.require(:user_list).permit :user_name_or_email
  end
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.avatar.attach(params[:user][:avatar])
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catelogies_helper.rb
module CatelogiesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/catelogies/_form.html.erb
<%= form_with(model: catelogy, local: true) do |form| %>
  <% if catelogy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(catelogy.errors.count, "error") %> prohibited this catelogy from being saved:</h2>

      <ul>
        <% catelogy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :catelogyName %>
    <%= form.text_area :catelogyName %>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/catelogies/edit.html.erb
<h1>Editing Catelogy</h1>

<%= render 'form', catelogy: @catelogy %>

<%= link_to 'Show', @catelogy %> |
<%= link_to 'Back', catelogies_path %>

app/views/catelogies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catelogies</h1>

<table>
  <thead>
    <tr>
      <th>catelogyName</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catelogies.each do |catelogy| %>
      <tr>
        <td><%= catelogy.catelogyName %></td>
        <td><%= link_to 'Show', catelogy %></td>
        <td><%= link_to 'Edit', edit_catelogy_path(catelogy) %></td>
        <td><%= link_to 'Destroy', catelogy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catelogy', new_catelogy_path %>

app/views/catelogies/new.html.erb
<h1>New Catelogy</h1>

<%= render 'form', catelogy: @catelogy %>

<%= link_to 'Back', catelogies_path %>

app/views/catelogies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>catelogyName:</strong>
  <%= @catelogy.catelogyName %>
</p>

<%= link_to 'Edit', edit_catelogy_path(@catelogy) %> |
<%= link_to 'Back', catelogies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= bootstrap_form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.rich_text_area :content, label: "content" %>
  </div>

  <div class="field">
    <%= form.select :user_id, options_for_select(User.pluck(:name, :id)), class: "form-control mb-4", label: "User Name" %>
  </div>

   <div class="field">
    <%= form.select :catelogy_id, options_for_select(Catelogy.pluck(:catelogyName, :id)), class: "form-control mb-4", label: "Catelogy Name" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<div class="container">

<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost, class: "btn btn-primary" %> |
<%= link_to 'Back', microposts_path, class: "btn btn-secondary" %>
</div>

app/views/microposts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>
<div class="row">
<%= search_form_for @q do |f| %>
<div class="input-group mb-3 col-sm-12">
  <input type="search_field" class="form-control col-ml-2" name="value" placeholder="input name or email" aria-label="input name or email" aria-describedby="button-addon2">
  
  <select class="custom-select" name="catelogyValue" id="inputGroupSelect01">
    <option value="" selected>Choose...</option>
    <% @micropostsAll.uniq.each do |micropost| %>
      <option  value="<%=micropost.catelogy.id%>"><%= micropost.catelogy.catelogyName %></option>
    <%end%>
  </select>

  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Seach</button>
  </div>
</div>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Category</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
  <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user.name %></td>
        <td><%= micropost.catelogy.catelogyName %></td>
        <td><%= link_to 'Show', micropost, class: "btn btn-primary" %> <%= link_to 'Edit', edit_micropost_path(micropost), class: "btn btn-primary" %> <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @microposts, theme: "twitter-bootstrap-4", pagination_class: "pagination-sm pagination-centered",  nav_class: "d-inline-b"%>
<br>
</div>
<%= link_to 'New Micropost', new_micropost_path, class: "btn btn-primary" %>
</div>

app/views/microposts/new.html.erb
<div class ="container">
    
end
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path, class: "btn btn-secondary" %>
</div>

app/views/microposts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user.name%>
</p>
<p>
  <strong>catelogy_Name:</strong>
  <%= @micropost.catelogy.catelogyName %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost), class: "btn btn-primary" %> |
<%= link_to 'Back', microposts_path, class: "btn btn-secondary" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %><br>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<div class="row">
<%= search_form_for @q do |f| %>
<div class="input-group mb-3 col-sm-12">
  <input type="search_field" class="form-control col-ml-2" name="value" placeholder="input name or email" aria-label="input name or email" aria-describedby="button-addon2">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Seach</button>
  </div>
</div>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= image_tag(user.avatar) if user.avatar.attached? %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users, theme: "twitter-bootstrap-4", pagination_class: "pagination-sm pagination-centered",  nav_class: "d-inline-b"%>
<br>
</div>
<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= image_tag(@user.avatar) if @user.avatar.attached? %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>